namespace:
  name: sandbox
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: hemanthkandukuri/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 10
resources:
  requests:
    memory: 64Mi
    CPU: 250m
  limits:
    memory: 128Mi
    CPU: 500m

livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
